"use client";
import { useState } from 'react'

export const formulario = {
  title: 'Lesley Forms',
  description: 'Generated by create next app',


}



export default function RootLayout({ children }) {
  // declarar uma nova variavel, dados com state e atribuir o objeto

  const [data, setData] = useState({
    name: '',
    email: '',
    assunto: '',
    conteudo: ''
  });


  // receber os dados do formulário

  const valorInput = e => setData({ ...data, [e.target.name]: e.target.value });

  const sendMsg = (e) => {

    e.preventDefault();
    console.log(`nome: ${data.nome}`);
    console.log(`assunto: ${data.assunto}`);
    console.log(`email: ${data.email}`);
    console.log(`conteudo: ${data.conteudo}`);
  }

  return (
    <html lang="pt-br">
      <body >
        <h1>Formulário</h1>
        <form onSubmit={sendMsg}>
          <label>Name:</label>
          <input type='text' name='nome' placeholder='digite o seu nome' onChange={valorInput} /><br /><br />

          <label>email:</label>
          <input type='email' name='email' placeholder='digite o seu email' onChange={valorInput}/><br /><br />

          <label>Assunto:</label>
          <input type='text' name='assunto' placeholder='digite o assunto' onChange={valorInput}/><br /><br />

          <label>Conteúdo:</label>
          <textarea name="conteudo" cols='30' rows='10' placeholder="digite o cnteudo da mensagem" onChange={valorInput}></textarea ><br /><br />

          <button type="submit">Enviar</button>
        </form>

      </body>


    </html>
  )
}
